## Libraries

In [1]:
#import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#load data
def load_data(df):
    return pd.read_csv(file_path)



In [3]:
file_path = '../data/raw/flight_df (2).csv'

df = load_data(file_path)
df.head()

Age  Class  Flight Distance  Inflight wifi service  \
0   26      3             2062                      2   
1   52      3              680                      5   
2   28      1              188                      3   
3   54      3              453                      3   
4   40      1              775                      4   

   Departure/Arrival time convenient  Ease of Online booking  Gate location  \
0                                  3                       3              3   
1                                  5                       5              5   
2                                  5                       3              4   
3                                  5                       5              5   
4                                  3                       3              3   

   Food and drink  Online boarding  Seat comfort  ...  Baggage handling  \
0               2                2             2  ...                 3   
1               3                4             4  ...                 4   
2               3                3             3  ...                 4   
3               3                4             4  ...                 3   
4               4                4             4  ...                 3   

   Checkin service  Inflight service  Cleanliness  Departure Delay in Minutes  \
0                3                 3            2                           0   
1                4                 4            4                          18   
2                4                 5            3                           0   
3                4                 3            1                          91   
4                3                 3            4                           0   

   Arrival Delay in Minutes  Gender_Male  Loyal Customer  Business Travel  \
0                         0            0               1                1   
1                         2            0               1                1   
2                         0            1               1                0   
3                        80            0               1                1   
4                         0            1               1                1   

   satisfied  
0          0  
1          1  
2          0  
3          0  
4          0  

[5 rows x 23 columns]

## EDA 

In [4]:
def explore_data(df):
    number_rows = df.shape[0]
    number_features = df.shape[1]
    data_types = df.dtypes

    print(f'Number of rows: {number_rows}')
    print(f'\nNumber of columns: {number_features}')
    print(f'\nData types: ')
    print(data_types)

explore_data(df)

Number of rows: 20000

Number of columns: 23

Data types: 
Age                                  int64
Class                                int64
Flight Distance                      int64
Inflight wifi service                int64
Departure/Arrival time convenient    int64
Ease of Online booking               int64
Gate location                        int64
Food and drink                       int64
Online boarding                      int64
Seat comfort                         int64
Inflight entertainment               int64
On-board service                     int64
Leg room service                     int64
Baggage handling                     int64
Checkin service                      int64
Inflight service                     int64
Cleanliness                          int64
Departure Delay in Minutes           int64
Arrival Delay in Minutes             int64
Gender_Male                          int64
Loyal Customer                       int64
Business Travel                      i

In [5]:
#functions to perform EDA
def perform_eda(df):
    duplicates = df.duplicated().sum()
    missing_values = df.isna().sum()

    print(f'Number of Duplicate Rows: {duplicates}')
    print(f'\nNumber of Missing Values: {missing_values}')

perform_eda(df)

Number of Duplicate Rows: 0

Number of Missing Values: Age                                  0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
Gender_Male                          0
Loyal Customer                       0
Business Travel                      0
satisfied                            0
dtype: int64


In [6]:
#summary statistics
statistics = df.describe().T
statistics

count        mean          std   min  \
Age                                20000.0    39.47725    15.108901   7.0   
Class                              20000.0     2.02780     0.963054   1.0   
Flight Distance                    20000.0  1188.54800  1001.136957  31.0   
Inflight wifi service              20000.0     2.72795     1.326886   0.0   
Departure/Arrival time convenient  20000.0     3.05610     1.531134   0.0   
Ease of Online booking             20000.0     2.75110     1.396799   0.0   
Gate location                      20000.0     2.97135     1.279575   0.0   
Food and drink                     20000.0     3.20210     1.332383   0.0   
Online boarding                    20000.0     3.25530     1.348485   0.0   
Seat comfort                       20000.0     3.43910     1.323434   1.0   
Inflight entertainment             20000.0     3.34910     1.333348   0.0   
On-board service                   20000.0     3.38535     1.278451   0.0   
Leg room service                   20000.0     3.35085     1.316602   0.0   
Baggage handling                   20000.0     3.62365     1.186837   1.0   
Checkin service                    20000.0     3.30285     1.259131   1.0   
Inflight service                   20000.0     3.63555     1.184017   0.0   
Cleanliness                        20000.0     3.28265     1.311734   0.0   
Departure Delay in Minutes         20000.0    14.31835    36.451829   0.0   
Arrival Delay in Minutes           20000.0    14.69825    36.899857   0.0   
Gender_Male                        20000.0     0.49065     0.499925   0.0   
Loyal Customer                     20000.0     0.81785     0.385978   0.0   
Business Travel                    20000.0     0.68790     0.463362   0.0   
satisfied                          20000.0     0.43305     0.495510   0.0   

                                     25%    50%     75%     max  
Age                                 27.0   40.0    51.0    85.0  
Class                                1.0    2.0     3.0     3.0  
Flight Distance                    414.0  842.0  1733.0  4983.0  
Inflight wifi service                2.0    3.0     4.0     5.0  
Departure/Arrival time convenient    2.0    3.0     4.0     5.0  
Ease of Online booking               2.0    3.0     4.0     5.0  
Gate location                        2.0    3.0     4.0     5.0  
Food and drink                       2.0    3.0     4.0     5.0  
Online boarding                      2.0    3.0     4.0     5.0  
Seat comfort                         2.0    4.0     5.0     5.0  
Inflight entertainment               2.0    4.0     4.0     5.0  
On-board service                     2.0    4.0     4.0     5.0  
Leg room service                     2.0    4.0     4.0     5.0  
Baggage handling                     3.0    4.0     5.0     5.0  
Checkin service                      3.0    3.0     4.0     5.0  
Inflight service                     3.0    4.0     5.0     5.0  
Cleanliness                          2.0    3.0     4.0     5.0  
Departure Delay in Minutes           0.0    0.0    12.0  1305.0  
Arrival Delay in Minutes             0.0    0.0    13.0  1280.0  
Gender_Male                          0.0    0.0     1.0     1.0  
Loyal Customer                       1.0    1.0     1.0     1.0  
Business Travel                      0.0    1.0     1.0     1.0  
satisfied                            0.0    0.0     1.0     1.0

In [9]:
#function to check all unique values and anomalies

def check_col_values(df):
    print('Check all columns for anomalies \n')

    #loop throguh each column i nthe data frame
    for column_name in df.columns:
        print(f'Unique Values in {column_name}')
        print(df[column_name].unique())
        print('\n')

check_col_values(df)


Check all columns for anomalies 

Unique Values in Age
[26 52 28 54 40 79 41 24 49 59 21 57 25 22 29 48  9 30 42 17 32 44 27 43
 46 37 53 23 12 33 10  7 15 65 20 34 31 39 56  8 60 36 69 58 62 51 47 16
 63 38 72 70 64 18 71 35 45 68 55 11 67 14 19 50 66 61 13 77 80 85 73 75
 74 78 76]


Unique Values in Class
[3 1 2]


Unique Values in Flight Distance
[2062  680  188 ... 3504 2875 1515]


Unique Values in Inflight wifi service
[2 5 3 4 0 1]


Unique Values in Departure/Arrival time convenient
[3 5 1 4 0 2]


Unique Values in Ease of Online booking
[3 5 1 2 0 4]


Unique Values in Gate location
[3 5 4 1 2 0]


Unique Values in Food and drink
[2 3 4 5 1 0]


Unique Values in Online boarding
[2 4 3 0 5 1]


Unique Values in Seat comfort
[2 4 3 5 1]


Unique Values in Inflight entertainment
[2 4 3 5 1 0]


Unique Values in On-board service
[3 4 1 5 2 0]


Unique Values in Leg room service
[3 4 1 2 5 0]


Unique Values in Baggage handling
[3 4 5 1 2]


Unique Values in Checkin service
[3 4 2